# image docker du pipeline (pour chaque job) par défaut
image: python:3.13-slim-bookworm

# étapes du pipeline à exécuter dans l'ordre
stages:
  - testing
  - qualifying


# nom arbitraire d'un job
test:
  stage: testing
  # association entre un job et un/des runner(s)
  tags:
    - formation
  # commandes de préparation avant l'exécution du job
  before_script:
    - cd app
    - python3 -m venv v_env
    - source v_env/bin/activate
    - pip3 install -r requirements.txt
    - pip3 install -r requirements-dev.txt
  # script à exécuter
  script:
    - pytest -v -m "not e2e"

quality:
  stage: qualifying
  tags:
    - formation
  script:
    - sleep 10
    - echo "QUALITY"